PLUGIN_ZIG_WASM_TARGET := wasm32-wasi
PLUGIN_ZIG_EXTRA_FLAGS := -lc \
  -DSQLITE_ENABLE_MEMSYS3 \
  -DSQLITE_OMIT_LOAD_EXTENSION \
  -DSQLITE_THREADSAFE=0 \
  -DSQLITE_OMIT_WAL \
  -DSQLITE_DEFAULT_MEMSTATUS=0 \
  -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 \
  -DSQLITE_LIKE_DOESNT_MATCH_BLOBS \
  -DSQLITE_MAX_EXPR_DEPTH=0 \
  -DSQLITE_OMIT_DECLTYPE \
  -DSQLITE_OMIT_DEPRECATED \
  -DSQLITE_OMIT_PROGRESS_CALLBACK \
  -DSQLITE_OMIT_SHARED_CACHE \
  -DSQLITE_USE_ALLOCA \
  -DSQLITE_TEMP_STORE=3
PLUGIN_C_SOURCES := $(PLUGIN_DIR)/sql/main.c $(PLUGIN_DIR)/sql/vendor/sqlite3.c
PLUGIN_EXTRA_DEPS := $(wildcard $(PLUGIN_DIR)/sql/vendor/*.h)
