// Code generated by wit-bindgen-go. DO NOT EDIT.

package scaler

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// TileMapShape is used for storage in variant or result types.
type TileMapShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(TileMap{})]byte
}

func lift_TileMap(f0 *TileLayer, f1 uint32, f2 *DataEntry, f3 uint32) (v TileMap) {
	v.Layers = cm.LiftList[cm.List[TileLayer]](f0, f1)
	v.Props = cm.LiftList[cm.List[DataEntry]](f2, f3)
	return
}

func lift_DoorSize(f0 uint32, f1 uint32) (v DoorSize) {
	v.Width = (uint32)(f0)
	v.Height = (uint32)(f1)
	return
}

func lift_DoorSizesConfig(f0 uint32, f1 uint32, f2 uint32, f3 uint32, f4 uint32, f5 uint32, f6 uint32, f7 uint32) (v DoorSizesConfig) {
	v.North = lift_DoorSize(f0, f1)
	v.East = lift_DoorSize(f2, f3)
	v.South = lift_DoorSize(f4, f5)
	v.West = lift_DoorSize(f6, f7)
	return
}

func lift_OptionDoorSizesConfig(f0 uint32, f1 uint32, f2 uint32, f3 uint32, f4 uint32, f5 uint32, f6 uint32, f7 uint32, f8 uint32) (v cm.Option[DoorSizesConfig]) {
	if f0 == 0 {
		return
	}
	return (cm.Option[DoorSizesConfig])(cm.Some[DoorSizesConfig](lift_DoorSizesConfig((uint32)(f1), (uint32)(f2), (uint32)(f3), (uint32)(f4), (uint32)(f5), (uint32)(f6), (uint32)(f7), (uint32)(f8))))
}

func lift_ScaleConfig(f0 uint32, f1 uint32, f2 uint32, f3 uint32, f4 uint32, f5 uint32, f6 uint32, f7 uint32, f8 uint32, f9 uint32) (v ScaleConfig) {
	v.ScaleFactor = (uint32)(f0)
	v.DoorSizes = lift_OptionDoorSizesConfig(f1, f2, f3, f4, f5, f6, f7, f8, f9)
	return
}
