// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package scaler represents the exported interface "gams:scaler/scaler@1.0.0".
package scaler

import (
	"go.bytecodealliance.org/cm"
)

// DataEntry represents the tuple "gams:scaler/scaler@1.0.0#data-entry".
//
//	type data-entry = tuple<string, string>
type DataEntry [2]string

// TileLayer represents the record "gams:scaler/scaler@1.0.0#tile-layer".
//
//	record tile-layer {
//		width: u32,
//		data: list<u32>,
//		props: list<data-entry>,
//	}
type TileLayer struct {
	_     cm.HostLayout      `json:"-"`
	Width uint32             `json:"width"`
	Data  cm.List[uint32]    `json:"data"`
	Props cm.List[DataEntry] `json:"props"`
}

// TileMap represents the record "gams:scaler/scaler@1.0.0#tile-map".
//
//	record tile-map {
//		layers: list<tile-layer>,
//		props: list<data-entry>,
//	}
type TileMap struct {
	_      cm.HostLayout      `json:"-"`
	Layers cm.List[TileLayer] `json:"layers"`
	Props  cm.List[DataEntry] `json:"props"`
}

// DoorSize represents the record "gams:scaler/scaler@1.0.0#door-size".
//
//	record door-size {
//		width: u32,
//		height: u32,
//	}
type DoorSize struct {
	_      cm.HostLayout `json:"-"`
	Width  uint32        `json:"width"`
	Height uint32        `json:"height"`
}

// DoorSizesConfig represents the record "gams:scaler/scaler@1.0.0#door-sizes-config".
//
//	record door-sizes-config {
//		north: door-size,
//		east: door-size,
//		south: door-size,
//		west: door-size,
//	}
type DoorSizesConfig struct {
	_     cm.HostLayout `json:"-"`
	North DoorSize      `json:"north"`
	East  DoorSize      `json:"east"`
	South DoorSize      `json:"south"`
	West  DoorSize      `json:"west"`
}

// ScaleConfig represents the record "gams:scaler/scaler@1.0.0#scale-config".
//
//	record scale-config {
//		scale-factor: u32,
//		door-sizes: option<door-sizes-config>,
//	}
type ScaleConfig struct {
	_           cm.HostLayout              `json:"-"`
	ScaleFactor uint32                     `json:"scale-factor"`
	DoorSizes   cm.Option[DoorSizesConfig] `json:"door-sizes"`
}
