// Code generated by wit-bindgen-go. DO NOT EDIT.

package scaler

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "gams:scaler/scaler@1.0.0".
var Exports struct {
	// Scale represents the caller-defined, exported function "scale".
	//
	//	scale: func(src: tile-map, config: scale-config) -> result<tile-map, string>
	Scale func(src TileMap, config ScaleConfig) (result cm.Result[TileMapShape, TileMap, string])
}
