// Code generated by wit-bindgen-go. DO NOT EDIT.

package scaler

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "gams:scaler@1.0.0".

//go:wasmexport gams:scaler/scaler@1.0.0#scale
//export gams:scaler/scaler@1.0.0#scale
func wasmexport_Scale(src0 *TileLayer, src1 uint32, src2 *DataEntry, src3 uint32, config0 uint32, config1 uint32, config2 uint32, config3 uint32, config4 uint32, config5 uint32, config6 uint32, config7 uint32, config8 uint32, config9 uint32) (result *cm.Result[TileMapShape, TileMap, string]) {
	src := lift_TileMap((*TileLayer)(src0), (uint32)(src1), (*DataEntry)(src2), (uint32)(src3))
	config := lift_ScaleConfig((uint32)(config0), (uint32)(config1), (uint32)(config2), (uint32)(config3), (uint32)(config4), (uint32)(config5), (uint32)(config6), (uint32)(config7), (uint32)(config8), (uint32)(config9))
	result_ := Exports.Scale(src, config)
	result = &result_
	return
}
