// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
#ifndef __BINDINGS_ADDER_H
#define __BINDINGS_ADDER_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Exported Functions from `docs:adder/add@0.1.0`
uint32_t exports_docs_adder_add_add(uint32_t x, uint32_t y);

#ifdef __cplusplus
}
#endif
#endif
