// Code generated by wit-bindgen-go. DO NOT EDIT.

package automap

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// TileMapShape is used for storage in variant or result types.
type TileMapShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(TileMap{})]byte
}

func lift_TileMap(f0 *TileLayer, f1 uint32, f2 *DataEntry, f3 uint32) (v TileMap) {
	v.Layers = cm.LiftList[cm.List[TileLayer]](f0, f1)
	v.Props = cm.LiftList[cm.List[DataEntry]](f2, f3)
	return
}

func lift_OptionTileMap(f0 uint32, f1 *TileLayer, f2 uint32, f3 *DataEntry, f4 uint32) (v cm.Option[TileMap]) {
	if f0 == 0 {
		return
	}
	return (cm.Option[TileMap])(cm.Some[TileMap](lift_TileMap((*TileLayer)(f1), (uint32)(f2), (*DataEntry)(f3), (uint32)(f4))))
}
