// Code generated by wit-bindgen-go. DO NOT EDIT.

package automap

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "gams:automap@1.0.0".

//go:wasmexport gams:automap/automap@1.0.0#apply
//export gams:automap/automap@1.0.0#apply
func wasmexport_Apply(rules0 *TileLayer, rules1 uint32, rules2 *DataEntry, rules3 uint32, input0 *TileLayer, input1 uint32, input2 *DataEntry, input3 uint32, target0 uint32, target1 *TileLayer, target2 uint32, target3 *DataEntry, target4 uint32) (result *cm.Result[TileMapShape, TileMap, string]) {
	rules := lift_TileMap((*TileLayer)(rules0), (uint32)(rules1), (*DataEntry)(rules2), (uint32)(rules3))
	input := lift_TileMap((*TileLayer)(input0), (uint32)(input1), (*DataEntry)(input2), (uint32)(input3))
	target := lift_OptionTileMap((uint32)(target0), (*TileLayer)(target1), (uint32)(target2), (*DataEntry)(target3), (uint32)(target4))
	result_ := Exports.Apply(rules, input, target)
	result = &result_
	return
}
