// Code generated by wit-bindgen-go. DO NOT EDIT.

package tiledetect

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// DetectSizeOutputShape is used for storage in variant or result types.
type DetectSizeOutputShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(DetectSizeOutput{})]byte
}

// ExtractOutputShape is used for storage in variant or result types.
type ExtractOutputShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(ExtractOutput{})]byte
}

func lift_ExtractConfig(f0 *uint8, f1 uint32, f2 uint32, f3 uint32, f4 uint32, f5 uint32) (v ExtractConfig) {
	v.SourceData = cm.LiftList[cm.List[uint8]](f0, f1)
	v.TileW = (uint32)(f2)
	v.TileH = (uint32)(f3)
	v.Tolerance = (uint32)(f4)
	v.SkipNthPixel = (uint32)(f5)
	return
}

// ExportTilesetOutputShape is used for storage in variant or result types.
type ExportTilesetOutputShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(ExportTilesetOutput{})]byte
}

func lift_ExportTilesetConfig(f0 *TileBankEntry, f1 uint32, f2 *uint8, f3 uint32, f4 uint32, f5 uint32, f6 uint32) (v ExportTilesetConfig) {
	v.Tilebank = cm.LiftList[cm.List[TileBankEntry]](f0, f1)
	v.SourceData = cm.LiftList[cm.List[uint8]](f2, f3)
	v.SourceCols = (uint32)(f4)
	v.TileW = (uint32)(f5)
	v.TileH = (uint32)(f6)
	return
}

// TileMapShape is used for storage in variant or result types.
type TileMapShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(TileMap{})]byte
}

func lift_TilemapData(f0 uint32, f1 uint32, f2 uint32, f3 uint32, f4 *uint32, f5 uint32) (v TilemapData) {
	v.Width = (uint32)(f0)
	v.Height = (uint32)(f1)
	v.TileW = (uint32)(f2)
	v.TileH = (uint32)(f3)
	v.Data = cm.LiftList[cm.List[uint32]](f4, f5)
	return
}

func lift_ExtractOutput(f0 *TileBankEntry, f1 uint32, f2 uint32, f3 uint32, f4 uint32, f5 uint32, f6 *uint32, f7 uint32) (v ExtractOutput) {
	v.Tilebank = cm.LiftList[cm.List[TileBankEntry]](f0, f1)
	v.Tilemap = lift_TilemapData(f2, f3, f4, f5, f6, f7)
	return
}
