// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package tiledetect represents the exported interface "gams:tile-detect/tile-detect@1.0.0".
package tiledetect

import (
	"go.bytecodealliance.org/cm"
)

// DataEntry represents the tuple "gams:tile-detect/tile-detect@1.0.0#data-entry".
//
//	type data-entry = tuple<string, string>
type DataEntry [2]string

// DetectSizeOutput represents the record "gams:tile-detect/tile-detect@1.0.0#detect-size-output".
//
//	record detect-size-output {
//		tile-w: u32,
//		tile-h: u32,
//		confidence: f64,
//	}
type DetectSizeOutput struct {
	_          cm.HostLayout `json:"-"`
	TileW      uint32        `json:"tile-w"`
	TileH      uint32        `json:"tile-h"`
	Confidence float64       `json:"confidence"`
}

// ExtractConfig represents the record "gams:tile-detect/tile-detect@1.0.0#extract-config".
//
//	record extract-config {
//		source-data: list<u8>,
//		tile-w: u32,
//		tile-h: u32,
//		tolerance: u32,
//		skip-nth-pixel: u32,
//	}
type ExtractConfig struct {
	_            cm.HostLayout  `json:"-"`
	SourceData   cm.List[uint8] `json:"source-data"`
	TileW        uint32         `json:"tile-w"`
	TileH        uint32         `json:"tile-h"`
	Tolerance    uint32         `json:"tolerance"`
	SkipNthPixel uint32         `json:"skip-nth-pixel"`
}

// TileBankEntry represents the record "gams:tile-detect/tile-detect@1.0.0#tile-bank-entry".
//
//	record tile-bank-entry {
//		id: u32,
//		source-index: u32,
//		hash: u64,
//	}
type TileBankEntry struct {
	_           cm.HostLayout `json:"-"`
	ID          uint32        `json:"id"`
	SourceIndex uint32        `json:"source-index"`
	Hash        uint64        `json:"hash"`
}

// TilemapData represents the record "gams:tile-detect/tile-detect@1.0.0#tilemap-data".
//
//	record tilemap-data {
//		width: u32,
//		height: u32,
//		tile-w: u32,
//		tile-h: u32,
//		data: list<u32>,
//	}
type TilemapData struct {
	_      cm.HostLayout   `json:"-"`
	Width  uint32          `json:"width"`
	Height uint32          `json:"height"`
	TileW  uint32          `json:"tile-w"`
	TileH  uint32          `json:"tile-h"`
	Data   cm.List[uint32] `json:"data"`
}

// ExtractOutput represents the record "gams:tile-detect/tile-detect@1.0.0#extract-output".
//
//	record extract-output {
//		tilebank: list<tile-bank-entry>,
//		tilemap: tilemap-data,
//	}
type ExtractOutput struct {
	_        cm.HostLayout          `json:"-"`
	Tilebank cm.List[TileBankEntry] `json:"tilebank"`
	Tilemap  TilemapData            `json:"tilemap"`
}

// ExportTilesetConfig represents the record "gams:tile-detect/tile-detect@1.0.0#export-tileset-config".
//
//	record export-tileset-config {
//		tilebank: list<tile-bank-entry>,
//		source-data: list<u8>,
//		source-cols: u32,
//		tile-w: u32,
//		tile-h: u32,
//	}
type ExportTilesetConfig struct {
	_          cm.HostLayout          `json:"-"`
	Tilebank   cm.List[TileBankEntry] `json:"tilebank"`
	SourceData cm.List[uint8]         `json:"source-data"`
	SourceCols uint32                 `json:"source-cols"`
	TileW      uint32                 `json:"tile-w"`
	TileH      uint32                 `json:"tile-h"`
}

// ExportTilesetOutput represents the record "gams:tile-detect/tile-detect@1.0.0#export-tileset-output".
//
//	record export-tileset-output {
//		data: list<u8>,
//		width: u32,
//		height: u32,
//		cols: u32,
//		rows: u32,
//	}
type ExportTilesetOutput struct {
	_      cm.HostLayout  `json:"-"`
	Data   cm.List[uint8] `json:"data"`
	Width  uint32         `json:"width"`
	Height uint32         `json:"height"`
	Cols   uint32         `json:"cols"`
	Rows   uint32         `json:"rows"`
}

// TileLayer represents the record "gams:tile-detect/tile-detect@1.0.0#tile-layer".
//
//	record tile-layer {
//		width: u32,
//		data: list<u32>,
//		props: list<data-entry>,
//	}
type TileLayer struct {
	_     cm.HostLayout      `json:"-"`
	Width uint32             `json:"width"`
	Data  cm.List[uint32]    `json:"data"`
	Props cm.List[DataEntry] `json:"props"`
}

// TileMap represents the record "gams:tile-detect/tile-detect@1.0.0#tile-map".
//
//	record tile-map {
//		layers: list<tile-layer>,
//		props: list<data-entry>,
//	}
type TileMap struct {
	_      cm.HostLayout      `json:"-"`
	Layers cm.List[TileLayer] `json:"layers"`
	Props  cm.List[DataEntry] `json:"props"`
}
