// Code generated by wit-bindgen-go. DO NOT EDIT.

package tiledetect

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "gams:tile-detect@1.0.0".

//go:wasmexport gams:tile-detect/tile-detect@1.0.0#detect-size
//export gams:tile-detect/tile-detect@1.0.0#detect-size
func wasmexport_DetectSize(path0 *uint8, path1 uint32, minSize0 uint32, maxSize0 uint32) (result *cm.Result[DetectSizeOutputShape, DetectSizeOutput, string]) {
	path := cm.LiftString[string]((*uint8)(path0), (uint32)(path1))
	minSize := (uint32)((uint32)(minSize0))
	maxSize := (uint32)((uint32)(maxSize0))
	result_ := Exports.DetectSize(path, minSize, maxSize)
	result = &result_
	return
}

//go:wasmexport gams:tile-detect/tile-detect@1.0.0#extract
//export gams:tile-detect/tile-detect@1.0.0#extract
func wasmexport_Extract(config0 *uint8, config1 uint32, config2 uint32, config3 uint32, config4 uint32, config5 uint32) (result *cm.Result[ExtractOutputShape, ExtractOutput, string]) {
	config := lift_ExtractConfig((*uint8)(config0), (uint32)(config1), (uint32)(config2), (uint32)(config3), (uint32)(config4), (uint32)(config5))
	result_ := Exports.Extract(config)
	result = &result_
	return
}

//go:wasmexport gams:tile-detect/tile-detect@1.0.0#export-tileset
//export gams:tile-detect/tile-detect@1.0.0#export-tileset
func wasmexport_ExportTileset(config0 *TileBankEntry, config1 uint32, config2 *uint8, config3 uint32, config4 uint32, config5 uint32, config6 uint32, config7 *uint8, config8 uint32) (result *cm.Result[ExportTilesetOutputShape, ExportTilesetOutput, string]) {
	config := lift_ExportTilesetConfig((*TileBankEntry)(config0), (uint32)(config1), (*uint8)(config2), (uint32)(config3), (uint32)(config4), (uint32)(config5), (uint32)(config6), (*uint8)(config7), (uint32)(config8))
	result_ := Exports.ExportTileset(config)
	result = &result_
	return
}

//go:wasmexport gams:tile-detect/tile-detect@1.0.0#to-tilemap
//export gams:tile-detect/tile-detect@1.0.0#to-tilemap
func wasmexport_ToTilemap(extractOutput0 *TileBankEntry, extractOutput1 uint32, extractOutput2 uint32, extractOutput3 uint32, extractOutput4 uint32, extractOutput5 uint32, extractOutput6 *uint32, extractOutput7 uint32) (result *cm.Result[TileMapShape, TileMap, string]) {
	extractOutput := lift_ExtractOutput((*TileBankEntry)(extractOutput0), (uint32)(extractOutput1), (uint32)(extractOutput2), (uint32)(extractOutput3), (uint32)(extractOutput4), (uint32)(extractOutput5), (*uint32)(extractOutput6), (uint32)(extractOutput7))
	result_ := Exports.ToTilemap(extractOutput)
	result = &result_
	return
}
