// Code generated by wit-bindgen-go. DO NOT EDIT.

package tiledetect

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "gams:tile-detect/tile-detect@1.0.0".
var Exports struct {
	// DetectSize represents the caller-defined, exported function "detect-size".
	//
	//	detect-size: func(path: string, min-size: u32, max-size: u32) -> result<detect-size-output,
	//	string>
	DetectSize func(path string, minSize uint32, maxSize uint32) (result cm.Result[DetectSizeOutputShape, DetectSizeOutput, string])

	// Extract represents the caller-defined, exported function "extract".
	//
	//	extract: func(config: extract-config) -> result<extract-output, string>
	Extract func(config ExtractConfig) (result cm.Result[ExtractOutputShape, ExtractOutput, string])

	// ExportTileset represents the caller-defined, exported function "export-tileset".
	//
	//	export-tileset: func(config: export-tileset-config) -> result<export-tileset-output,
	//	string>
	ExportTileset func(config ExportTilesetConfig) (result cm.Result[ExportTilesetOutputShape, ExportTilesetOutput, string])

	// ToTilemap represents the caller-defined, exported function "to-tilemap".
	//
	//	to-tilemap: func(extract-output: extract-output) -> result<tile-map, string>
	ToTilemap func(extractOutput ExtractOutput) (result cm.Result[TileMapShape, TileMap, string])
}
