// Code generated by wit-bindgen-go. DO NOT EDIT.

package automap

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "gams:automap/automap@1.0.0".
var Exports struct {
	// Apply represents the caller-defined, exported function "apply".
	//
	//	apply: func(rules: tile-map, input: tile-map, target: option<tile-map>) -> result<tile-map,
	//	string>
	Apply func(rules TileMap, input TileMap, target cm.Option[TileMap]) (result cm.Result[TileMapShape, TileMap, string])
}
