PLUGIN_WASM_COMPONENT := 1
PLUGIN_WIT_WORLD := gams:aseprite/aseprite-plugin@1.0.0
PLUGIN_COMPONENT_NAME := aseprite_plugin
PLUGIN_COMPONENT_SOURCES := $(PLUGIN_PATH)/component.c
PLUGIN_COMPONENT_EXTRA_DEPS := \
	$(PLUGIN_PATH)/stb_image.h
