// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
#include "calculator.h"
#include <stdlib.h>

// Imported Functions from `docs:adder/add@0.1.0`

__attribute__((__import_module__("docs:adder/add@0.1.0"), __import_name__("add")))
extern int32_t __wasm_import_docs_adder_add_add(int32_t, int32_t);

// Exported Functions from `docs:calculator/calculate@0.1.0`


// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Component Adapters

uint32_t docs_adder_add_add(uint32_t x, uint32_t y) {
  int32_t ret = __wasm_import_docs_adder_add_add((int32_t) (x), (int32_t) (y));
  return (uint32_t) (ret);
}

__attribute__((__export_name__("docs:calculator/calculate@0.1.0#eval-expression")))
int32_t __wasm_export_exports_docs_calculator_calculate_eval_expression(int32_t arg, int32_t arg0, int32_t arg1) {
  uint32_t ret = exports_docs_calculator_calculate_eval_expression(arg, (uint32_t) (arg0), (uint32_t) (arg1));
  return (int32_t) (ret);
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_calculator(void);
__attribute__((used))
void __component_type_object_force_link_calculator_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_calculator();
}
