// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
#ifndef __BINDINGS_CALCULATOR_H
#define __BINDINGS_CALCULATOR_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef uint8_t exports_docs_calculator_calculate_op_t;

#define EXPORTS_DOCS_CALCULATOR_CALCULATE_OP_ADD 0

// Imported Functions from `docs:adder/add@0.1.0`
extern uint32_t docs_adder_add_add(uint32_t x, uint32_t y);

// Exported Functions from `docs:calculator/calculate@0.1.0`
uint32_t exports_docs_calculator_calculate_eval_expression(exports_docs_calculator_calculate_op_t op, uint32_t x, uint32_t y);

#ifdef __cplusplus
}
#endif
#endif
