// Code generated by wit-bindgen-go. DO NOT EDIT.

package minimap

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// TileMapShape is used for storage in variant or result types.
type TileMapShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(TileMap{})]byte
}
