// Code generated by wit-bindgen-go. DO NOT EDIT.

package minimap

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "gams:minimap@1.0.0".

//go:wasmexport gams:minimap/minimap@1.0.0#gen
//export gams:minimap/minimap@1.0.0#gen
func wasmexport_Gen(tree0 *Node, tree1 uint32) (result *cm.Result[TileMapShape, TileMap, string]) {
	tree := cm.LiftList[Tree]((*Node)(tree0), (uint32)(tree1))
	result_ := Exports.Gen(tree)
	result = &result_
	return
}
