// Code generated by wit-bindgen-go. DO NOT EDIT.

package minimap

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "gams:minimap/minimap@1.0.0".
var Exports struct {
	// Gen represents the caller-defined, exported function "gen".
	//
	//	gen: func(tree: tree) -> result<tile-map, string>
	Gen func(tree Tree) (result cm.Result[TileMapShape, TileMap, string])
}
