// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package minimap represents the exported interface "gams:minimap/minimap@1.0.0".
package minimap

import (
	"go.bytecodealliance.org/cm"
)

// DataEntry represents the tuple "gams:minimap/minimap@1.0.0#data-entry".
//
//	type data-entry = tuple<string, string>
type DataEntry [2]string

// Node represents the record "gams:minimap/minimap@1.0.0#node".
//
//	record node {
//		data: list<data-entry>,
//		parent-id: s32,
//	}
type Node struct {
	_        cm.HostLayout      `json:"-"`
	Data     cm.List[DataEntry] `json:"data"`
	ParentID int32              `json:"parent-id"`
}

// Tree represents the list "gams:minimap/minimap@1.0.0#tree".
//
//	type tree = list<node>
type Tree cm.List[Node]

// TileLayer represents the record "gams:minimap/minimap@1.0.0#tile-layer".
//
//	record tile-layer {
//		width: u32,
//		data: list<u32>,
//		props: list<data-entry>,
//	}
type TileLayer struct {
	_     cm.HostLayout      `json:"-"`
	Width uint32             `json:"width"`
	Data  cm.List[uint32]    `json:"data"`
	Props cm.List[DataEntry] `json:"props"`
}

// TileMap represents the record "gams:minimap/minimap@1.0.0#tile-map".
//
//	record tile-map {
//		layers: list<tile-layer>,
//		props: list<data-entry>,
//	}
type TileMap struct {
	_      cm.HostLayout      `json:"-"`
	Layers cm.List[TileLayer] `json:"layers"`
	Props  cm.List[DataEntry] `json:"props"`
}
