// Code generated by wit-bindgen-go. DO NOT EDIT.

package treegenerator

func lift_GenerateTreeConfig(f0 uint32, f1 uint32, f2 uint32, f3 uint32) (v GenerateTreeConfig) {
	v.NodeCount = (uint32)(f0)
	v.MaxDepth = (uint32)(f1)
	v.MaxBranching = (uint32)(f2)
	v.RootBranches = (uint32)(f3)
	return
}
