// Code generated by wit-bindgen-go. DO NOT EDIT.

package treegenerator

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "gams:tree-generator/tree-generator@1.0.0".
var Exports struct {
	// Gen represents the caller-defined, exported function "gen".
	//
	//	gen: func(config: generate-tree-config) -> result<tree, string>
	Gen func(config GenerateTreeConfig) (result cm.Result[Tree, Tree, string])
}
