// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package treegenerator represents the exported interface "gams:tree-generator/tree-generator@1.0.0".
package treegenerator

import (
	"go.bytecodealliance.org/cm"
)

// DataEntry represents the tuple "gams:tree-generator/tree-generator@1.0.0#data-entry".
//
//	type data-entry = tuple<string, string>
type DataEntry [2]string

// Node represents the record "gams:tree-generator/tree-generator@1.0.0#node".
//
//	record node {
//		data: list<data-entry>,
//		parent-id: s32,
//	}
type Node struct {
	_        cm.HostLayout      `json:"-"`
	Data     cm.List[DataEntry] `json:"data"`
	ParentID int32              `json:"parent-id"`
}

// Tree represents the list "gams:tree-generator/tree-generator@1.0.0#tree".
//
//	type tree = list<node>
type Tree cm.List[Node]

// GenerateTreeConfig represents the record "gams:tree-generator/tree-generator@1.0.0#generate-tree-config".
//
//	record generate-tree-config {
//		node-count: u32,
//		max-depth: u32,
//		max-branching: u32,
//		root-branches: u32,
//	}
type GenerateTreeConfig struct {
	_            cm.HostLayout `json:"-"`
	NodeCount    uint32        `json:"node-count"`
	MaxDepth     uint32        `json:"max-depth"`
	MaxBranching uint32        `json:"max-branching"`
	RootBranches uint32        `json:"root-branches"`
}
