// Code generated by wit-bindgen-go. DO NOT EDIT.

package treegenerator

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "gams:tree-generator@1.0.0".

//go:wasmexport gams:tree-generator/tree-generator@1.0.0#gen
//export gams:tree-generator/tree-generator@1.0.0#gen
func wasmexport_Gen(config0 uint32, config1 uint32, config2 uint32, config3 uint32) (result *cm.Result[Tree, Tree, string]) {
	config := lift_GenerateTreeConfig((uint32)(config0), (uint32)(config1), (uint32)(config2), (uint32)(config3))
	result_ := Exports.Gen(config)
	result = &result_
	return
}
