// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
#ifndef __BINDINGS_RANDOM_PROVIDER_H
#define __BINDINGS_RANDOM_PROVIDER_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

typedef struct {
  uint8_t *ptr;
  size_t len;
} random_provider_list_u8_t;

// Exported Functions from `wasi:random/random@0.2.0`
void exports_wasi_random_random_get_random_bytes(
    uint64_t len, random_provider_list_u8_t *ret);
uint64_t exports_wasi_random_random_get_random_u64(void);

// Exported Functions from `gams:random/seeded-random@1.0.0`
void exports_gams_random_seeded_random_set_seed(uint64_t seed);
uint64_t exports_gams_random_seeded_random_get_seed(void);
uint64_t exports_gams_random_seeded_random_get_generation(void);

// Helper Functions

void random_provider_list_u8_free(random_provider_list_u8_t *ptr);

#ifdef __cplusplus
}
#endif
#endif
