// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
#include "random_provider.h"
#include <stdlib.h>

// Exported Functions from `wasi:random/random@0.2.0`

__attribute__((__weak__, __export_name__("cabi_post_wasi:random/random@0.2.0#get-random-bytes")))
void __wasm_export_exports_wasi_random_random_get_random_bytes_post_return(uint8_t * arg0) {
  size_t len = *((size_t*) (arg0 + sizeof(void*)));
  if (len > 0) {
    uint8_t *ptr = *((uint8_t **) (arg0 + 0));
    for (size_t i = 0; i < len; i++) {
      uint8_t *base = ptr + i * 1;
      (void) base;
    }
    free(ptr);
  }
}


// Exported Functions from `gams:random/seeded-random@1.0.0`




// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

__attribute__((__aligned__(sizeof(void*))))
static uint8_t RET_AREA[(2*sizeof(void*))];

// Helper Functions

void random_provider_list_u8_free(random_provider_list_u8_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

// Component Adapters

__attribute__((__export_name__("wasi:random/random@0.2.0#get-random-bytes")))
uint8_t * __wasm_export_exports_wasi_random_random_get_random_bytes(int64_t arg) {
  random_provider_list_u8_t ret;
  exports_wasi_random_random_get_random_bytes((uint64_t) (arg), &ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + sizeof(void*))) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

__attribute__((__export_name__("wasi:random/random@0.2.0#get-random-u64")))
int64_t __wasm_export_exports_wasi_random_random_get_random_u64(void) {
  uint64_t ret = exports_wasi_random_random_get_random_u64();
  return (int64_t) (ret);
}

__attribute__((__export_name__("gams:random/seeded-random@1.0.0#set-seed")))
void __wasm_export_exports_gams_random_seeded_random_set_seed(int64_t arg) {
  exports_gams_random_seeded_random_set_seed((uint64_t) (arg));
}

__attribute__((__export_name__("gams:random/seeded-random@1.0.0#get-seed")))
int64_t __wasm_export_exports_gams_random_seeded_random_get_seed(void) {
  uint64_t ret = exports_gams_random_seeded_random_get_seed();
  return (int64_t) (ret);
}

__attribute__((__export_name__("gams:random/seeded-random@1.0.0#get-generation")))
int64_t __wasm_export_exports_gams_random_seeded_random_get_generation(void) {
  uint64_t ret = exports_gams_random_seeded_random_get_generation();
  return (int64_t) (ret);
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_random_provider(void);
__attribute__((used))
void __component_type_object_force_link_random_provider_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_random_provider();
}
