PLUGIN_ZIG_WASM_TARGET := wasm32-wasi
PLUGIN_ZIG_EXTRA_FLAGS := -lc \
  -I$(PLUGIN_DIR)/sql-vec/vendor \
  -DSQLITE_ENABLE_MEMSYS3 \
  -DSQLITE_OMIT_LOAD_EXTENSION \
  -DSQLITE_THREADSAFE=0 \
  -DSQLITE_OMIT_WAL \
  -DSQLITE_DEFAULT_MEMSTATUS=0 \
  -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 \
  -DSQLITE_LIKE_DOESNT_MATCH_BLOBS \
  -DSQLITE_MAX_EXPR_DEPTH=0 \
  -DSQLITE_OMIT_DECLTYPE \
  -DSQLITE_OMIT_DEPRECATED \
  -DSQLITE_OMIT_PROGRESS_CALLBACK \
  -DSQLITE_OMIT_SHARED_CACHE \
  -DSQLITE_USE_ALLOCA \
  -DSQLITE_TEMP_STORE=3 \
  -DSQLITE_CORE \
  -DSQLITE_VEC_STATIC \
  -DSQLITE_VEC_OMIT_FS
PLUGIN_C_SOURCES := \
  $(PLUGIN_DIR)/sql-vec/main.c \
  $(PLUGIN_DIR)/sql-vec/vendor/sqlite3.c \
  $(PLUGIN_DIR)/sql-vec/vendor/sqlite-vec.c
PLUGIN_EXTRA_DEPS := $(wildcard $(PLUGIN_DIR)/sql-vec/vendor/*.h)
